services:
  postgres:
    image: postgres:16
    container_name: spendly-postgres
    environment:
      POSTGRES_DB: ${DB_SPENDLY_DATABASE}
      POSTGRES_USER: ${DB_SPENDLY_USERNAME}
      POSTGRES_PASSWORD: ${DB_SPENDLY_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: spendly-backend
    depends_on:
      - postgres
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_SPENDLY_URL: jdbc:postgresql://postgres:5432/${DB_SPENDLY_DATABASE}
      DB_SPENDLY_USERNAME: ${DB_SPENDLY_USERNAME}
      DB_SPENDLY_PASSWORD: ${DB_SPENDLY_PASSWORD}
    ports:
      - "8080:8080"

volumes:
  postgres_data: